# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Proxy/bin/Win32/Release'
    Contents: 'proxy.dll'
    TargetFolder: '/dist/x86'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'Proxy/bin/x64/Release'
    Contents: 'proxy.dll'
    TargetFolder: '/dist/x64'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'docs/'
    Contents: 'dist_readme.md,doorstop_config.ini'
    TargetFolder: '/dist/x64'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'docs/'
    Contents: 'dist_readme.md,doorstop_config.ini'
    TargetFolder: '/dist/x86'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'DoorstopTest/bin/Release'
    Contents: 'Doorstop.dll'
    TargetFolder: '/dist/x86/Example.dll'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'DoorstopTest/bin/Release'
    Contents: 'Doorstop.dll'
    TargetFolder: '/dist/x64/Example.dll'
    OverWrite: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/x86'
    archiveFile: 'bins/Doorstop_$(Build.BuildId)_x86.zip'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/x64'
    archiveFile: 'bins/Doorstop_$(Build.BuildId)_x64.zip'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'bins'
    ArtifactName: 'Doorstop'