# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x64'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Proxy/bin/Win32/Release'
    Contents: 'proxy.dll'
    TargetFolder: '$(Build.SourcesDirectory)/dist/x86'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Proxy/bin/x64/Release'
    Contents: 'proxy.dll'
    TargetFolder: '$(Build.SourcesDirectory)/dist/x64'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/docs/'
    Contents: |
     dist_readme.md
     doorstop_config.ini
    TargetFolder: '$(Build.SourcesDirectory)/dist/x64'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/docs/'
    Contents: |
     dist_readme.md
     doorstop_config.ini
    TargetFolder: '$(Build.SourcesDirectory)/dist/x86'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/DoorstopTest/bin/Release'
    Contents: 'Doorstop.dll'
    TargetFolder: '$(Build.SourcesDirectory)/dist/x86/Example'
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/DoorstopTest/bin/Release'
    Contents: 'Doorstop.dll'
    TargetFolder: '$(Build.SourcesDirectory)/dist/x64/Example'
    OverWrite: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/x86/'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Doorstop_$(Build.BuildId)_x86.zip'
    includeRootFolder: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/x64/'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Doorstop_$(Build.BuildId)_x64.zip'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Doorstop'    